### ISSUE TITLE
problem with changing origin on Equation screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#113]
On the _Equations_ screen, there are problems when repositioning the origin.  The vectors shown on the graph for the current equation selection don't move.  But when you switch to one of the other equations, then the vectors will jump around, as if they were translated with the origin. 

To reproduce:
1. start sim
2. go to _Equations_ screen. You'll see this:

<img width="1090" alt="screenshot_1341" src="https://user-images.githubusercontent.com/3046552/63305174-1b00b600-c2a3-11e9-9df8-c490ae97d512.png">

3. Move the origin, like this. Note that the vectors don't move with the origin (should they?)

<img width="1092" alt="screenshot_1342" src="https://user-images.githubusercontent.com/3046552/63305198-353a9400-c2a3-11e9-9d64-7c0a90de5b98.png">

4. Switch to the "a - b = c" equation.  Note that the vectors jump to an entirely different place relative to the origin.  Similarly for the "a + b + c = 0" equation.

<img width="1093" alt="screenshot_1343" src="https://user-images.githubusercontent.com/3046552/63305220-4c798180-c2a3-11e9-9c25-eb9634291d7c.png">

This doesn't seem correct. We are changing the equation, not translating the vectors, and vectors "a" and "b" should look identical regardless of which equation is selected.  

@arouinfar please advise on how this should behave.

**Comment by pixelzoom** [comment]
8/22/19 design meeting:

* When moving the origin, vectors for the unselected equation scenes should not move relative to the graph bounds.
* Make each equation scene have its own origin.

**Comment by brandonLi8** [comment]
@pixelzoom @arouinfar wanted to check in; if we are "[Making] each equation scene have its own origin" we are **significantly** changing how the entire sim works.

In the past, @arouinfar and I agreed with me that it should be one "origin" (graph):
https://github.com/phetsims/vector-addition/issues/68#issuecomment-512338516

This becomes problematic because `BaseVectors` aren't part of a graph. They are part of 3 graphs. The api for all vectors relies on passing a single `VectorSet` and a `Graph`. If there were 3 graphs, the baseVectors wouldn't have both of these.

`VectorSet` is required to be passed to Vectors because on the polar scene, Vectors Snap to each other and the Vector needs to know about the other vectors on the graph. It is hard to see this api changing (to somehow allow 3 vector sets).

The same goes with `Graph`, which raises larger problems. `Graph` is needed because Vector's view positions don't change but their model positions change when the origin is moving. Thus the Vector needs to observe the Graph (requiring a single Graph being passed)


In my personal opinion, the bug outlined by @pixelzoom can be resolved with one extra link inside of the loop of `EquationVector`, small refactor of `EquationVectorSum` and its node.

**Comment by pixelzoom** [comment]
On hold until #148 is resolved.

**Comment by arouinfar** [comment]
In #148 we decided that the equation radio options `a + b = c`, `a - b = c`, and `a + b + c = 0` will NOT be separate scenes. I suspect this issue can be closed, but I'll leave that up to @pixelzoom.

**Comment by pixelzoom** [comment]
Yep, this can be closed. 🎉
