### ISSUE TITLE
layout of stuff above the graph in Equation screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#128]
8/22/19 design meeting, @arouinfar @ariel-phet @kathy-phet:  

Work on layout of this stuff on Equation screen.  @ariel-phet suggested moving equation radio buttons to left of Equation accordion box.

<img width="772" alt="screenshot_1355" src="https://user-images.githubusercontent.com/3046552/63545474-baf95200-c4e4-11e9-8fb5-0597295b02ff.png">

**Comment by pixelzoom** [comment]
In the above commit, I made all of the Vector Values toggle boxes the same size.  The one in the _Equations_ screen was a bit wider. 

In https://github.com/phetsims/vector-addition/issues/133#issuecomment-524667069 said:
> @pixelzoom it was decided when @arouinfar and I had a design meeting to make the VectorValuesToggleBox larger only for the Equation screen.
> 
> Edit: can't find any comments about this... don't know why it wasn't documented. But I can remember that we did this because the coefficients on the equation screen make the labels larger, requiring more space.

I don 't see any ill effects due to the coefficients, but I'll revert and let @arouinfar decide.

**Comment by pixelzoom** [comment]
The screenshot below shows the new layout.

Remaining issues/questions:
* Contents of the 'Equation' accordion box shift slightly when switching between Cartesian (a,b,c) and polar (d,e,f) snap modes.
* Should 'Vector Values' accordion box perhaps be _below_ the 'Equations' accordion box?

@arouinfar @ariel-phet please review in master with high priority.

<img width="1018" alt="screenshot_1503" src="https://user-images.githubusercontent.com/3046552/65549045-f6b77b00-ded9-11e9-87cc-573739404820.png">

**Comment by pixelzoom** [comment]
Keeping myself on the list of assignees, so that I can address stuff shifting around.

**Comment by arouinfar** [comment]
Reviewed this with @ariel-phet and we both like the combined panel encompassing the equation and radio buttons. 

We would like to swap the order of the equation and the radioButtonGroup. Flow-wise, we want students playing with the spinners in the equation before comparing the different equations types. Since students generally work left-to-right, the equation should remain on the left.

One polish that @ariel-phet mentioned is that the operands in the equation look a bit further up than in the corresponding radio button.
![image](https://user-images.githubusercontent.com/8419308/65633068-7c016500-df98-11e9-9dd6-68971c9ea56d.png)
![image](https://user-images.githubusercontent.com/8419308/65633080-80c61900-df98-11e9-9973-4f3834fec3d3.png)

The equation operands are very likely already centered on the spinners, but he suggested shifting them down a pixel, so they more aligned with the letters. 

> Should 'Vector Values' accordion box perhaps be below the 'Equations' accordion box?

I'd leave the ordering as it is now. I think it looks better with the Vector Values on top. It's also pretty common to add new panels or UI components below the ones that appeared on previous screens.

**Comment by kathy-phet** [comment]
Just did a quick skim of this issue since I saw it pop up in my email. I like putting the equation buttons into the accordian. It also allows someone to ask "what is this equation" by hiding the accordian box altogether. 

One thing I'm not sure about is putting the equation on the left. I know students generally work left-to right, but it feels like the spinners are more attractive being close to all the other controls on the right and close to where you set the unit vectors. And sort of easier to coordinate. So I would favor keeping that layout sort of open and maybe trying a couple interviews one way and a couple interviews the other way to see what helps students have a good flow through the sim. 

I'm also a righty so that influences me as well.

**Comment by pixelzoom** [comment]
> We would like to swap the order of the equation and the radioButtonGroup.  ...

OK, but...  Once you've chosen an equation, you'll probably want to adjust coefficients and base vectors.  Putting the radio buttons on the left makes all of the pickers (coefficients and base vectors) as close as possible.  Putting the radio buttons on the right results in a big spatial separation between pickers. 

It sounds like @kathy-phet is advocating doing interviews on this.  That would require a query parameter to select layout.  Let me know if you'd like me to add a query parameter, and what the default layout should be.

> One polish that @ariel-phet mentioned is that the operands in the equation look a bit further up than in the corresponding radio button. ... The equation operands are very likely already centered on the spinners, but he suggested shifting them down a pixel, so they more aligned with the letters.

I currently have no ability to shift anything. All of the pieces of the equation are in an `HBox` (horizontal box) that has full control of the positioning, and vertically aligns all centers.  This is the same problem that prevented alignment of baselines.  If we want to address this, then I'd recommend aligning baselines of all text, then fudging the positions of the pickers.  Let me know if you want me to proceed with this.

**Comment by pixelzoom** [comment]
In the above commit, I rewrote `EquationTypeNode` so that baselines of text Nodes remain aligned, and NumberPickers are positioned empirically.   Examples below.  This looks much better to me.  @arouinfar @ariel-phet OK?

<img width="743" alt="screenshot_1523" src="https://user-images.githubusercontent.com/3046552/65643575-49af3200-dfaf-11e9-8272-98a640d6a496.png">
<img width="738" alt="screenshot_1524" src="https://user-images.githubusercontent.com/3046552/65643582-4caa2280-dfaf-11e9-926c-7b668b5c2cb7.png">

**Comment by pixelzoom** [comment]
In the above commit, I added query parameter `equationButtons`, with values `left` and `right` (default), which specified where the buttons appear in the Equation accordion box.

@arouinfar please review in [1.0.0-dev.24](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.24/phet/vector-addition_en_phet.html).

With `?equationButtons=left`:

<img width="739" alt="screenshot_1525" src="https://user-images.githubusercontent.com/3046552/65644364-474dd780-dfb1-11e9-81df-dff25cf00fcc.png">
<img width="742" alt="screenshot_1526" src="https://user-images.githubusercontent.com/3046552/65644373-4ae15e80-dfb1-11e9-9bda-d1d6790f3d1c.png">
<img width="740" alt="screenshot_1527" src="https://user-images.githubusercontent.com/3046552/65644380-4e74e580-dfb1-11e9-8346-547d022c1ecd.png">

With `?equationButtons=right` (the default):

<img width="742" alt="screenshot_1528" src="https://user-images.githubusercontent.com/3046552/65644391-5765b700-dfb1-11e9-9669-27baac90213c.png">
<img width="741" alt="screenshot_1529" src="https://user-images.githubusercontent.com/3046552/65644396-592f7a80-dfb1-11e9-9e3b-53fc6b0cd575.png">
<img width="738" alt="screenshot_1530" src="https://user-images.githubusercontent.com/3046552/65644398-5a60a780-dfb1-11e9-9656-f8f9387dee70.png">

**Comment by kathy-phet** [comment]
Seeing these, I vote for the buttons on the left, spinners on the right.

**Comment by pixelzoom** [comment]
My preference is the same as @kathy-phet.

**Comment by arouinfar** [comment]
I think @pixelzoom and @kathy-phet raise some good points in regards to keeping the equation spinners on the right side of the panel. I'm happy to test out the layout in interviews, so thanks for the query parameter @pixelzoom. Everything seems to be working in dev.24.

Aesthetically, I would agree that the equation radioButtonGroup looks best on the left, as the varying length of the equation can create some trapped space. I plan on testing this version in the interviews first.

> In the above commit, I rewrote EquationTypeNode so that baselines of text Nodes remain aligned, and NumberPickers are positioned empirically.

Looks good to me! @ariel-phet what do you think of the screenshots in https://github.com/phetsims/vector-addition/issues/128#issuecomment-535244105?

**Comment by pixelzoom** [comment]
I've moved the issue of where to place the radio buttons to https://github.com/phetsims/vector-addition/issues/196.

**Comment by pixelzoom** [comment]
I've moved the issue of where to place the radio buttons to https://github.com/phetsims/vector-addition/issues/196.   So if @ariel-phet is good with the alignment of the equation with pickers, this issue can be closed.

**Comment by ariel-phet** [comment]
Alignment of equation looks good. Closing
