### ISSUE TITLE
what is the scope of the "Sum" checkboxes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#157]
What is the scope of the "Sum" checkboxes?  In some screens, it applies to both scenes.   In others, it's specific to scene.   It seems like the state of the "Sum" checkbox should apply to both scenes, similar to the other checkboxes in the other checkboxes in the "graph controls" panel.   But this is complicated by the fact that the _Lab_ screen has 2 "Sum" checkboxes.

@arouinfar please advise.

**Comment by arouinfar** [comment]
> It seems like the state of the "Sum" checkbox should apply to both scenes, similar to the other checkboxes in the other checkboxes in the "graph controls" panel.

Agreed!

> But this is complicated by the fact that the Lab screen has 2 "Sum" checkboxes.

This does make it a bit less clear-cut, but I think it would still feel strange for the sum to be scene-dependent for this one case. An alternative would be for the sum to always only apply to a single scene, but that UX is also a bit wonky since the other checkboxes are global.

@pixelzoom let's take the global approach, and make the sum checkbox apply to both scenes on all screens.

**Comment by pixelzoom** [comment]
@arouinfar I'm not clear on what do you'd like to do for the 2 Sum checkboxes in the Lab screen.  Is the first checkbox linked to the same global Property in both scenes, and similarly for the 2nd checkbox?

**Comment by pixelzoom** [comment]
I went ahead and make the Lab screen behave like the other screens; the Property associated with the Sum checkbox now affects both of the screen's scenes.   @arouinfar let me know if this is OK, especially for the Lab screen.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom, thanks!
