### ISSUE TITLE
representation of on-axis vectors

### ISSUE THREAD

**Issue by veillette** [phetsims/vector-addition#16]
![image](https://user-images.githubusercontent.com/7633344/58996580-0c335880-87b6-11e9-873f-f00923b6e9f1.png)

In the flash simulation, the projection of the vectors on the x and y axis are slightly offset. 
Should this feature be implemented as well?

**Comment by arouinfar** [comment]
Discussed some in the 6/6/19 design meeting.

Some offset is desirable, but we want to avoid large shifts since this component style is meant to represent the projection on the axes.

1. The offset could be tied to the z-ordering. The topmost vector's components could be on the axes, with lower layers being offset. This would mean that the active vector's components would never have any offset, which could help reinforce that this component style really is the projection on the axis.
2. The offset could be determined by the order the vector is added to the play area (Flash behavior)
3. The offset could be global. Components of vector a are always on the axes, components for vector b are shifted by 1 px, and components for vector c are shifted by 2 px. This could end up looking a bit weird if vector c is the only vector in the play area.

@veillette any thoughts here? My personal preference would be option (1), but I don't know if that is feasible or not.

**Comment by brandonLi8** [comment]
From #74 @arouinfar said:
>No, not yet. Can you evaluate the options presented in #16 (comment), and let me know what you think?

In my opinion, both option 1 and 2 are feasible (option 1 would be slightly harder). 

@chrisklus  suggested that we could also consider not doing an offset but change the sizing of the  vector similar to how number line integers does it:
![image](https://user-images.githubusercontent.com/42391580/61653717-28149000-ac78-11e9-85d5-7909b610af2a.png)
This would be based on the size of the vector. @arouinfar thoughts?

**Comment by brandonLi8** [comment]
Thinking about it now, I'm not sure that @chrisklus 's suggestion works since many of the vectors are the same colors.


@arouinfar is it an absolute must to have an offset? At this point, option 1 looks like the most feasible, but I think it would feel weird to have component vectors switch spots when the active vector is changed.

**Comment by arouinfar** [comment]
@brandonLi8 thanks for evaluating the options. I think the situation in Number Line isn't that analogous to Vector Addition for a few reasons
* Components would generally have the same color (exception being different vector groups on Lab)
* Thickness has some physicality to it, and I worry if students may try to extract some meaning from it, despite it being meaningless.

Let's check in with the design team and see how they feel about option (1) before you start implementation @brandonLi8.

**Comment by brandonLi8** [comment]
See https://github.com/phetsims/vector-addition/issues/19#issuecomment-515198188.

It was decided that no offset will be added, but some form of 'highlight' should be added. Closing this issue, as I progress of this will be tracked in #19.
