### ISSUE TITLE
EquationVectorNode is not used

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#171]
`EquationVectorNode` is not used. I'm wondering if it should be deleted or somehow incorporated.   If you `grunt checkout 07756f3d9e86e72f8f6c0d27197324c640048b9e`, you'll be in the state that was used to publish 1.0.0-dev.12, just before I started working on this sim.

@brandonLi8 any insight?

**Comment by brandonLi8** [comment]
@pixelzoom I created it to update the label content of equation vectors when the coefficient changes.

However, I combated this change by adding this in `VectorLabelNode`:
```
      // Observe changes to the model vector, and update the label node
      this.labelMultilink = new Multilink( [ valuesVisibleProperty,
          rootVector.tailPositionProperty,
          rootVector.tipPositionProperty,
          activeVectorProperty ],
        updateLabelNode );
```
which changes the label content when the tip changes (which changes when the coefficient is changed)

However, I think there might be a bug that should be tested on touch screen devices.
If you:
1. Make vector "a" be <2,0> with a coefficient of 1 on the equation screen
2. Change the vector to <1,0> by clicking on the x component number picker but at the *same* time on a touch screen device change the coefficient to 2 which would keep the components at <2,0>

I suspect that the label content would still say its a coefficient of 1 since the tip or the tail didn't change. Now, this is looking at the sha you pasted above, and might be fixed.


If I am wrong and there isn't a bug, i think it's safe to delete `EquationVectorNode`, but if there is, there might be larger problems and this node might need to be integrated.

**Comment by pixelzoom** [comment]
Thanks much for the info @brandonLi8, I'll investigate.

**Comment by pixelzoom** [comment]
I don't see any bug with the multitouch scenario described in https://github.com/phetsims/vector-addition/issues/171#issuecomment-530598372.  Since multitouch will general be vetted in a separate issue, I'm going to go ahead and delete `EquationVectorNode`, then close this issue.
