### ISSUE TITLE
pointer areas for vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#183]
Running with `?showPointerAreas`, blue dashed lines are `mouseArea`, red dashed lines are `touchArea`.

I see 2 cases where the `mouseArea` is dilated to make vectors easier to grab -- they are shown below, along with screenshots.  But I see nothing done for `touchArea`.  @arouinfar what do you want to do here?

In RootVectorNode:

```js
      if ( rootVector.magnitude > 0 && this.arrowNode.shape ) {
        // Make the arrow easier to grab
        this.arrowNode.mouseArea = this.arrowNode.shape.getOffsetShape( 3 );
      }
```

<img width="237" alt="screenshot_1487" src="https://user-images.githubusercontent.com/3046552/64999097-cd786880-d8a3-11e9-88ad-f6e0b3b71f64.png">

In VectorCreatorPanelSlot:

```js
      // Make the iconNode easier to grab
      iconNode.mouseArea = iconNode.shape.getOffsetShape( 8 );
```

<img width="95" alt="screenshot_1488" src="https://user-images.githubusercontent.com/3046552/64999104-d10bef80-d8a3-11e9-9ec9-b0229f05441f.png">

**Comment by arouinfar** [comment]
@pixelzoom the dilated `mouseArea` in the screenshots in https://github.com/phetsims/vector-addition/issues/183#issue-494317615 look pretty reasonable, so I think that would be a good place to start with the `touchArea`.

The vectors in the play area are fairly easy to manipulate on an iPad, but might be a little tricky on mobile, so a slight `touchArea` dilation to match the `mouseArea` would probably do the trick.

The vectors are incredibly difficult to grab from the toolbox on an iPad. I've also noticed that the vector doesn't pop out of the toolbox when it's tapped, but it does with a mouse. This is a bit frustrating because it's not that clear when the vector has been successfully grabbed or not.

**Comment by pixelzoom** [comment]
I've set toucArea to be the same as mouseArea, for vectors on the graph and in the toolbox.  @arouinfar please review in master.  If this is reasonable, we can tweak further when we do general review of pointer areas as part of the master checklist.

**Comment by arouinfar** [comment]
@pixelzoom looks good on master, thanks!
