### ISSUE TITLE
Possible slight overlap of lengthened x-axis labels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#218]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/434
When the x-axis label is translated it can slightly overlap with the control elements to the right of the graph.  This can be seen very slightly with stringTest=long, but is more noticeable with rtl.  Since this length of translation is unlikely to occur this can probably be closed without doing anything if you agree.
**Steps to reproduce**
1. Use stringTest long or rtl
2. Go to any screen
3. Move the origin to move the x-axis up and down and observe overlap with tools on the right.

**Visuals**
![longlap](https://user-images.githubusercontent.com/41024075/66238579-1d816880-e6b5-11e9-9bdd-b9ef089824ef.png)
![moreoverlap](https://user-images.githubusercontent.com/41024075/66238580-1e19ff00-e6b5-11e9-9853-7311340488c0.png)
![potentialoverlap](https://user-images.githubusercontent.com/41024075/66238581-1e19ff00-e6b5-11e9-8319-279fef81d2c2.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Vector Addition‬
URL: https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html
Version: 1.0.0-dev.36 2019-10-03 17:23:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Looks like `maxWidth` for the x-axis label should be a little smaller.

**Comment by pixelzoom** [comment]
Fixed in the above commits in master.  

With no stringTest:

<img width="340" alt="screenshot_1573" src="https://user-images.githubusercontent.com/3046552/66356396-11e9a800-e928-11e9-9ada-6e52655c2076.png">

With `?stringTest=long`:

<img width="342" alt="screenshot_1572" src="https://user-images.githubusercontent.com/3046552/66356401-1910b600-e928-11e9-83f4-3f7ab737ebd9.png">

With `?stringTest=rtl`:

<img width="414" alt="screenshot_1571" src="https://user-images.githubusercontent.com/3046552/66356411-1f069700-e928-11e9-87b3-bdddd60b96b7.png">

Closing.
