### ISSUE TITLE
Can we increase touch areas around checkboxes?

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/vector-addition#244]
On the phone, it was also hard to activate the checkboxes with reliability. It would help to increase touch areas as was done in Blackbody. What do you think? 
![image](https://user-images.githubusercontent.com/5096804/67104393-157cfa80-f184-11e9-8ec0-325a1f47b79e.png)

**Comment by pixelzoom** [comment]
Yes we can, @arouinfar do you concur?  

Also note that this sim has already been through review off pointer areas at least twice (see #205 and #216).  Should we modify the PhET process for this review, to ensure that the entire team is engaged?

**Comment by arouinfar** [comment]
> Yes we can, @arouinfar do you concur?

Yes, but I think it's only necessary for the touchArea. 

> Also note that this sim has already been through review of pointer areas at least twice (see #205 and #216). Should we modify the PhET process for this review, to ensure that the entire team is engaged?

I tested on my phone (Pixel XL, at the time) and on an iPad. The differences in experience probably come down to @kathy-phet's phone screen being smaller than mine. QA has an iPhone test device. I forget the generation, but its screen is on the smaller side. Perhaps dev testing could include `pointerArea` testing on that device.

**Comment by kathy-phet** [comment]
Sorry I meant touch areas. editting

**Comment by kathy-phet** [comment]
Also, I think the design standard should be to increase the touch areas on all check boxes to be like shown in the above screenshot by default. I realize sometimes checkboxes are closer or further from each other, so it can't be really a default, but I think if it was the design norm to make them as big as possible without overlapping, it would make the usability the best on phones.

**Comment by pixelzoom** [comment]
> Also, I think the design standard should be to increase the touch areas on all check boxes to be like shown in the above screenshot by default. I

I agree. Unfortunately there's no support for that (and no way to easily add that support) in common code. 

This turned into major work because the checkboxes did not have uniform height.  Some of them (e.g. grid, 'c', 'f') are a bit taller.  So I either had to hardcode each checkbox's touchArea individually or address the height problem.  Neither as easy, so I chose the latter, which is better for longterm maintenance and (imo) looks better because the vertical spacing between the checkbox boxes is now uniform.

@arouinfar @kathy-phet please review in [1.0.0-dev.46](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.46/phet/vector-addition_en_phet.html).  Please review with and without `?showPointerAreas`.  Verify that each checkbox works correctly, because I had to touch every one of them in nontrivial ways.

**Comment by kathy-phet** [comment]
Works better for me! Fewer mis-fires. In playing I found that it would be good if we could increase the touch area of the equation coefficients more too. It led to a bunch of mis-fires when I used it, and it seemed like it would not conflict with anything to dialate it more so similar in size to the unit vectors spinner which was easy to use. (I will make a new issue).

**Comment by arouinfar** [comment]
Thanks @pixelzoom. The checkboxes look good, appear to all be in working order, and are easy to use on mobile.

**Comment by pixelzoom** [comment]
Reopening because @kathy-phet said:
>  In playing I found that it would be good if we could increase the touch area of the equation coefficients more too.

Please describe. How much more (percentage)? Width and height?

And while we're at it... Do you have the same issue with the base vector pickers?  

Here's what they look like now:

<img width="358" alt="screenshot_1610" src="https://user-images.githubusercontent.com/3046552/67130921-0fa50a80-f1c0-11e9-9276-e672f7ca6511.png">

**Comment by pixelzoom** [comment]
Ah, I see that the pickers are being addressed in #245.  Re-closing.
