### ISSUE TITLE
User feedback: scale of axes

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/vector-addition#270]
> First time trying out the HTML version of this sim and I noticed that the biggest vertical component we can draw is 25 units from the origin (29 if you go below it). Is there any way to zoom out on the scale? I see you can change quadrants by moving the origin but that doesn't allow you a longer y axis. I just want to know if I have to change my materials to reflect this!

It sounds like this user is going to modify their materials, but thought I should create an issue for this in case there are other suggestions to accommodate larger vertical components.

**Comment by pixelzoom** [comment]
I'm guessing that the user would have to change their material because the axes had different ranges in the Flash version. (I can't run Flash on my machine, and I'm not familiar with the Flash version.)

Adding zoom to the axes would be a significant design effort (where do we put the controls? what are the zoom levels? what are the limits?...) and a _big_ implementation effort.  So my recommendation is to tell the user that they need to change their materials.

**Comment by arouinfar** [comment]
The Flash version had a much bigger grid, but it also was full of occlusion issues. The usable portion of the grid is roughly 50x40, which is actually pretty similar to the HTML5 dimensions.
![Screenshot Capture - 2020-09-28 - 23-03-44](https://user-images.githubusercontent.com/8419308/94514637-f46bb900-01de-11eb-9b10-4068bb562282.png)

There really isn't anything we can do to increase the size of the grid, short of adding a zoom feature. Zoom controls would be expensive and I don't think they would provide any real payoff. The learning goals can be met with the current range.

Back to @oliver-phet to respond to the user.

**Comment by oliver-phet** [comment]
Reply to user sent.
