### ISSUE TITLE
CT: Can only drag while pressed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#281]
This error started on 7/15 @ 12:51PM, and has been failing on every CT cycle.  

> vector-addition : fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1721069505235/vector-addition/vector-addition_en.html?continuousTest=%7B%22test%22%3A%5B%22vector-addition%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1721069505235%22%2C%22timestamp%22%3A1721071329437%7D&brand=phet&ea&fuzz
ERROR: QUERY: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: Can only drag while pressed
STACK: Error: Assertion failed: Can only drag while pressed
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1721069505235/assert/js/assert.js:45:13)
    at assert (PressListener.ts:528:14)
    at call (DragListener.ts:268:35)
    at apply (PhetioAction.ts:162:16)
    at execute (DragListener.ts:419:21)
    at drag (PressListener.ts:901:13)
    at inputEvent (Input.ts:1869:91)
    at dispatchToListeners (Input.ts:1818:9)
    at dispatchEvent (Input.ts:1726:11)
    at branchChangeEvents (Input.ts:1666:9)
    at moveEvent (Input.ts:427:11)
    at apply (PhetioAction.ts:162:16)
    at execute (Input.ts:1201:25)
    at mouseMove (InputFuzzer.js:302:24)
    at mouseMove (InputFuzzer.js:43:11)
    at action (InputFuzzer.js:107:6)
    at fuzzEvents (SimDisplay.ts:221:23)
    at fuzzInputEvents (Sim.ts:1026:44)

**Comment by pixelzoom** [comment]
To reproduce manually in main:

1. Start the sim, go to the Explore 1D screen.
2. Drag a vector from the toolbox to the graph.
3. Attempt to drag the vector back to the toolbox.  As soon as it leaves the bounds of the graph, the assertion failure occurs.

**Comment by jonathanolson** [comment]
On it. It broke between 4 scenery commits, one of which was the "interrupt input on visibility change".

**Comment by jonathanolson** [comment]
`interruptSubtreeOnInvisible: false` on VectorLabelNode seems to resolve this. My guess is that it queues up a few listeners to fire when it is dragged out of the bounds (and the label becomes invisible)... the one that makes it invisible happens BEFORE it calls the drag listener.

Ideally we'd want to recognize that we've been interrupted, and NOT fire anything (instead of asserting out).

**Comment by pixelzoom** [comment]
We could certainly go with the `interruptSubtreeOnInvisible: false` workaround on VectorLabelNode.  But then this problem is likely to come up again.   As you said, the more correct/general fix is to recognize that we've been interrupted, and NOT fire anything (instead of asserting out).

**Comment by jonathanolson** [comment]
Have the more general fix in testing. I'll also want to apply this to press/drag listener's "up" since it could happen to that also.

I'm also planning on committing the `interruptSubtreeOnVisible:false` to revert the sim behavior back to its original (it is a bit weird that it interrupts the drag when moving from the graph).

**Comment by jonathanolson** [comment]
Pushed up, @pixelzoom can you verify?

**Comment by pixelzoom** [comment]
CT seems to be happy. Glad we could get a general fix - thanks! Closing.
