### ISSUE TITLE
Text not scaling properly with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/vector-addition#287]
For https://github.com/phetsims/qa/issues/1165 and https://github.com/phetsims/qa/issues/1166, on all screens with ?stringTest=dynamic, the text and number displays in the Vector Values accordion box doesn't scale correctly. The size of the number displays shouldn't change, nor should the labels for the first 2 number displays. 
<img width="604" alt="Screenshot 2024-11-08 at 1 32 51 PM" src="https://github.com/user-attachments/assets/1dc8ecd9-5886-44e8-bbf1-0ea4f84ca3f3">

@pixelzoom is looking into it.

**Comment by pixelzoom** [comment]
Fix applied to main and 1.1 branches (for both sims) in the above commits.  This was a royal pain because changes had been made throughout main in https://github.com/phetsims/vector-addition/commit/cd5bc527340f2e76d7ef87b9859231cbd5bcb326 and https://github.com/phetsims/vector-addition-equations/commit/ab968ffbea80c0f79e3ede19d0594c24ee14c52f.  I had to revert my work, revert those changes, then reapply my work.  

@Nancy-Salpepi please review in main. If it looks OK, change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
Sorry it was such a pain! Looks good on main now 🙂

**Comment by pixelzoom** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/1168 with:
https://phet-dev.colorado.edu/html/vector-addition/1.1.0-rc.2/phet/vector-addition_all_phet.html?stringTest=dynamic

Ready for testing in https://github.com/phetsims/qa/issues/1169 with:
https://phet-dev.colorado.edu/html/vector-addition-equations/1.1.0-rc.2/phet/vector-addition-equations_all_phet.html?stringTest=dynamic
