### ISSUE TITLE
Panning without dropping vector focus suggestion

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/vector-addition#288]
**Device**
iPad 10th gen
**OS**
iPadOS 18.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/1165
It can sometimes be easier to select smaller vectors on a touch screen by zooming in. However, when you try to pan or unzoom to look at the Vector Values box, the vector is unselected. It may be a good quality of life touch if panning doesn't unselect the vector. But if that isn't possible it isn't a large issue.
**Visuals**

https://github.com/user-attachments/assets/2626dab7-899a-4e40-a331-a7cf305a0f02

**Comment by pixelzoom** [comment]
Discussed with @arouinfar. This is unfortunately an unsolvable problem, and will be closed as "won't fix".

Clicking anywhere within the bounds of the graph selects a vector or clears the selection.  If zoomed in and all you can see is the graph, you have no choice but to click in the graph.  And we can't prevent clicks from being propagated to the sim when zoomed in, because that would make the sim unusable when zoomed in.

So if you want to pan without changing the selection, you need to click somewhere outside the bounds of the graph.
