### ISSUE TITLE
Removing vectors from the grid

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#46]
I think we decided at one of our design meetings that we will eventually want to delete individual vectors one at a time.

Martin and I have a few questions:
1. Have we decided on the way to do this?
2. What happens on the inspect a vector panel when you delete one vector? (The most feasible way of doing this is just reseting if so it would say 'select a vector')

Feel free to add to this

**Comment by veillette** [comment]
@arouinfar : 
To put this in context, the question is: do we want to remove vectors from the graph only in bulk (through the reset button or eraser button), or will we allow to remove the vectors individually (through some process that can be specified later)?

This decision has some impacts of memory management since removing the vectors in bulk, would make it easier to handle memory leak, since we can more easily handle all the listeners and observers attached to the vectors.

However, if we keep remove the vectors one at a time, then we should be more careful about removing the observers and listeners. 

In addition, if we remove the vectors one at a time, it impacts other design decisions which we have not tackled yet. @brandonLi8 mentions how we should deal with the inspectVectorPanel, but it also affects other such as how to deal with the sum.  

We are adding the meeting design label.

**Comment by brandonLi8** [comment]
@veillette , the sum would be the same. In essence, the sum is always the sum of the vectors that are on the graph. Deleting one makes the sum change, but we already have removal listeners.

Regarding observers and listeners: it wouldn't be too much of a hassle. What we have set up, is set up to already listen to removing one item at a time.

**Comment by brandonLi8** [comment]
Also @veillette , If i remember correctly, we decided that it is indeed necessary to remove one at a time because it would be annoying to have to remove all of the vectors on the lab screen because on the lab screen there is a potential to have lots of vectors.

I think we we were going to do something similar to the CCK delete button.

**Comment by veillette** [comment]
At the 6/27 design meeting, we decided that we would allow vectors to be removed one at a time. The  process to removed them will be similar to Area-builder.

**Comment by arouinfar** [comment]
For more details about removing vectors from the grid, see the [June 27 ](https://docs.google.com/document/d/1opnDgqIqIroo8VK0CbOyQ5608_g11MSGZXnFlI8k5Ds/edit#heading=h.99onqykklyu)meeting notes.

**Comment by arouinfar** [comment]
@brandonLi8 has the behavior discussed in the June 27 meeting implemented in master. Self-assigning to test it out and tune `vectorDragThreshold`.

**Comment by arouinfar** [comment]
@brandonLi8 let's bump up `vectorDragThreshold` to 10.

For smooth/fast drags, the vector pops off really seamlessly.
![fastDrag](https://user-images.githubusercontent.com/8419308/60845789-a5c99d80-a19a-11e9-8bb1-669d982ab6db.gif)

For slower drags, it takes a bit of effort to remove the vector. I think we want this to feel a bit sticky so users aren't accidentally removing vectors all the time.
![slowDrag](https://user-images.githubusercontent.com/8419308/60845790-a5c99d80-a19a-11e9-80ce-7faa6a0a0851.gif)

What seems a bit odd is that `vectorDragThreshold` is being applied in all cases, even if the cursor has left the grid. I think it would be better UX for the vector to be removed if the cursor leaves the grid OR the `vectorDragThreshold` has been exceeded, whichever happens first.
![verticalVector](https://user-images.githubusercontent.com/8419308/60845791-a5c99d80-a19a-11e9-84d9-8f298523b5a9.gif)

**Comment by brandonLi8** [comment]
> I think it would be better UX for the vector to be removed if the cursor leaves the grid OR the vectorDragThreshold has been exceeded, whichever happens first.
@arouinfar ay I see.  I agree and this certainly wouldn't be hard.
