### ISSUE TITLE
inconsistent use of fonts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/vector-addition#70]
Noted while playing with the sim in preparation for "quick review" #66.

Font usage is inconsistent.  There is a mix of serif and sans serif fonts, for the same symbols.  For example, see the partial screenshot below from the "Explore2D" screen, where "b'" is displayed in serif and sans serif - even within the accordion box.

It looks like all of the serif fonts occur in the vector notation (arrow above symbol). Does this have something to do with the use of `FormulaNode`? 

<img width="587" alt="screenshot_1277" src="https://user-images.githubusercontent.com/3046552/61190698-c2b01600-a65d-11e9-9eb8-d02f0c33e9ee.png">

**Comment by brandonLi8** [comment]
@pixelzoom, yes this has something to do with formula node. We use formula node on 'b' since we need the arrow, and I'm not sure how to change the font of formula node.

**Comment by arouinfar** [comment]
@brandonLi8 @pixelzoom variable names should use serif font and numbers should use sans-serif font, as has been the pattern in recent math sims. 

>see the partial screenshot below from the "Explore2D" screen, where "b'" is displayed in serif and sans serif - even within the accordion box.

@brandonLi8 I believe all of the readout labels should be serif since they are variable names.

**Comment by pixelzoom** [comment]
>  @brandonLi8 @pixelzoom variable names should use serif font and numbers should use sans-serif font, as has been the pattern in recent math sims.

Symbols (variable names) should use `MathSymbolFont`, which encapsulates the font used for symbols, making them easy to change in one place.  We do not want to be explicitly specifying "serif" in sim code.

**Comment by pixelzoom** [comment]
>  @brandonLi8 @pixelzoom variable names should use serif font and numbers should use sans-serif font, as has been the pattern in recent math sims.

Symbols (variable names) should use `MathSymbolFont`, which encapsulates the font _and style_ used for symbols, making them easy to change in one place.  We do not want to be explicitly specifying "serif" in sim code.

MathSymbolFont is currently `family: "Times New Roman", Times, serif'` and `style: 'italic'`.

**Comment by pixelzoom** [comment]
Btw... If `FormulaNode` can't use `MathSymbolFont` directly, then we should add something (constants or static method) to `MathSymbolFont` that allows `FormulaNode` to get what it needs.

**Comment by pixelzoom** [comment]
I took a quick look at `FormulaNode`.  It's not immediately obvious to me how to specify a font.  You'll probably have to ask the author, @jonathanolson.

**Comment by jonathanolson** [comment]
It would probably be good to talk about requirements. FormulaNode uses KaTeX, which has somewhat of a limited compatible font selection. See https://github.com/phetsims/sherpa/tree/master/katex/katex-0.5.1/fonts for a list of all fonts that we could potentially embed.

We've generated different preloads for use with FormulaNode that embed different fonts. It is likely we'd need to generate another preload that has additional fonts included.

To change the style of parts of a formula, it would mean including latex commands that would adjust the font style. For example, in the FormulaNode demo in ComponentsScreenView, `'\\forall \\mathbf{p}\\in\\mathbb{R}^2'` displays two different fonts:

![katex-font](https://user-images.githubusercontent.com/480878/61249088-af5e8280-a711-11e9-8af1-24626eaeb5f7.png)

Is one of those fonts in katex sufficient? Otherwise we'll probably need to handle things with a different approach.

**Comment by brandonLi8** [comment]
Fonts look good now. I forgot to tag a lot of commits.

Look at https://github.com/phetsims/vector-addition/issues/85 to track fonts on the vector label.
Look at https://github.com/phetsims/vector-addition/issues/74 to track fonts on the inspect a vector panel.

Assigning @chrisklus to review.

**Comment by pixelzoom** [comment]
Per 8/15/19 status meeting, reassigning to me for review.

**Comment by pixelzoom** [comment]
Fonts look great, nice work.  Closing.
