### ISSUE TITLE
Screen Icons

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#76]
I am approaching the point where I am running out of work to do. I think it is time to start thinking about screen icons.

**Comment by arouinfar** [comment]
@brandonLi8 are screen icons something you could generate in code? Since #56 is still outstanding, I don't want to spend much time on designing screen icons in Illustrator.

Here's a rough idea of what I'm thinking for icons. I'd want the grid off, and all labels hidden.

Explore 1D:
![image](https://user-images.githubusercontent.com/8419308/61646379-aa945400-ac66-11e9-89cf-917601b0cdc6.png)


Explore 2D:
![image](https://user-images.githubusercontent.com/8419308/61646353-93edfd00-ac66-11e9-96d7-ec4b78b3fbaf.png)

Lab:
![image](https://user-images.githubusercontent.com/8419308/61646344-89336800-ac66-11e9-995f-75ed2803f20b.png)

Equation:
![image](https://user-images.githubusercontent.com/8419308/61646325-728d1100-ac66-11e9-8c18-dd90de8ae84a.png)

**Comment by brandonLi8** [comment]
>@brandonLi8 are screen icons something you could generate in code.
Yes, I should be able to get these done fairly soon.

**Comment by brandonLi8** [comment]
@arouinfar I have finished the 'rough idea' icons:
![image](https://user-images.githubusercontent.com/42391580/61741771-d7239b00-ad4e-11e9-93eb-06084f0240a9.png)

Let me know if there are any adjustments to be made

**Comment by arouinfar** [comment]
Thanks @brandonLi8! I'll tag this for design meeting for team feedback.

**Comment by kathy-phet** [comment]
We reviewed the screens and we decided that 
1) we like the general direction
2) we want all the arrow stroke widths to be a consistent width across the icons
3) the Lab to look something like this: 
![image](https://user-images.githubusercontent.com/5096804/61905604-afffd180-aee6-11e9-8f69-06dd3692c88e.png)

**Comment by arouinfar** [comment]
@brandonLi8 I played around a bit with the Lab screen, and I think this would be a nice icon.

![image](https://user-images.githubusercontent.com/8419308/61910719-9ebcc200-aef2-11e9-82e4-aa446a961ece.png)

**Comment by brandonLi8** [comment]
@arouinfar, @kathy-phet, @ariel-phet I know that the thickness of the arrows came up at the design meeting.

I have figured out how to make the thickness the same for every icon.
We can go with:

1. thick:
![image](https://user-images.githubusercontent.com/42391580/61998329-9dfb6b80-b06b-11e9-9b18-2c1152406e6b.png)

2. medium:
![image](https://user-images.githubusercontent.com/42391580/61998334-bb303a00-b06b-11e9-964e-a74889bc1031.png)

3. thin: 
![image](https://user-images.githubusercontent.com/42391580/61998338-d0a56400-b06b-11e9-9acb-518d4406de4b.png)

My personal preference is either 2 or 1. Let me know what looks natural (btw, we can go even thinner or thicker).

**Comment by arouinfar** [comment]
@brandonLi8 I quite like option (2).

**Comment by brandonLi8** [comment]
Screen Icons are done (unless the design is going to change). 

Assigning @chrisklus to review implementation.

**Comment by pixelzoom** [comment]
Per 8/15/19 status meeting, reassigning to me for review.

**Comment by ariel-phet** [comment]
Screen icons look good
