### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#87]
From #81:
> - [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) Test on a version built using grunt --minify.mangle=false. There should be a GitHub issue showing the results of testing done by the primary developer.

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 50.5 |
| 1 | 64.2 |
| 2 | 78.9 |
| 3 | 88.1 |
| 5 | 108 |
| 7 | 123 |
| 10 | 151 |

Tested on:
https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.9/phet/vector-addition_en_phet.html?fuzz

Unfortunately, this is indicative of a memory leak. After looking at a glance, I was unable to find the source.

**Comment by brandonLi8** [comment]
After further testing with @chrisklus and by myself, I am still not able to find the cause.

**Comment by brandonLi8** [comment]
I use Path.setShape in various places throughout the sim.

I did find in Path's setShape documentation this:
```
    * NOTE: Be aware of the potential for memory leaks. If a Shape is not marked as immutable (with makeImmutable()),
     *       Path will add a listener so that it is updated when the Shape itself changes. If there is a listener
     *       added, keeping a reference to the Shape will also keep a reference to the Path object (and thus whatever
     *       Nodes are connected to the Path). For now, set path.shape = null if you need to release the reference
     *       that the Shape would have, or call dispose() on the Path if it is not needed anymore.
     *
```

So i went back and used makeImmutable on all shapes that were being used in setShape.
I even disposed of the Paths when needed.

However, when I went to testing if the memory leak was solved, the same results occurred (in fact, the memory went up even further).

At this point, I am not sure what to do.

**Comment by pixelzoom** [comment]
I'll have a look.

**Comment by pixelzoom** [comment]
This is the first I've looked a memory since I started working on the sim, just after 1.0.0-dev.12.  It still appears to be leaking.

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 54.4 |
| 1 | 68.4 |
| 2 | 95.3 |
| 3 | 97.7 |
| 4 | 98.1 |
| 5 | 103.0 | 
| 10 | 139.0 |

**Comment by pixelzoom** [comment]
In the commits above, I did some memory-management hygiene.

**Comment by pixelzoom** [comment]
Running with the _Equation_ screen only,  `?brand=phet&ea&screens=4&fuzz`, there appears to be no memory leak, and footprint stabilizes at ~44MB after ~5 minutes. That's reassuring, since the _Equation_ screen does not dynamically add/remove vectors; everything is created at startup.

**Comment by pixelzoom** [comment]
Running with the `Explore 2D` screen only, `?brand=phet&ea&screens=2&fuzz`.  If I remove the vector toolbox, so that no vectors can be created, then the memory leak is gone.  So the leak is definitely related to vector creation/deletion. 

To remove the vector toolbox, comment out line 198 in SceneNode, in method `addVectorCreatorPanel`:

`this.addChild( vectorCreatorPanel );`

**Comment by pixelzoom** [comment]
@samreid and I worked on this, and he identified that a reference to VectorNode was being retained by a DragListener.  This was interesting, because the DragListener is owned by the VectorNode, and looks like this:

```js
// @private drag listener for translating the vector
      this.translationDragListener = new DragListener( {
        pressCursor: options.arrowOptions.cursor,
        targetNode: this,
        locationProperty: tailLocationProperty,
...
```

We added a call to `this.translationDragListener.dispose()` in `dispose`, and the leak went away. So we suspected a problem in `DragListener`.  

Before committing the call to `this.translationDragListener.dispose()`, I decided to do a general cleanup of VectorNode, which is the subject of the commits immediately above.  After that cleanup, the call to `this.translationDragListener.dispose()` no longer appears to be needed (though I'll leave it in the code), and the memory leak is gone.   It's reassuring to know that there's isn't a problem with DragListeners, but frustrating to not be able to pinpoint what was wrong. 

I'll move on, and do another memory test table.

**Comment by pixelzoom** [comment]
Results of testing [1.0.0-dev.32](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.32/phet/vector-addition_en_phet.html) with `?fuzz`, macOS 10.14.6, Chrome 77.0.3865.90

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 52.2 |
| 1 | 61.4 |
| 2 | 61.6 |
| 3 | 62.8 |
| 4 | 62.9 |
| 5 | 63.9 |
| 10 | 67.3 |
| 15 | 65.3 |
| 20 | 65.5 |
| 25 | 67.8 |
| 30 | 67.1 |
| 45 | | 
| 60 | |

**Comment by pixelzoom** [comment]
After about 10 minutes of fuzzing, the sim footprint stabilizes and hovers ~66MB.  This seems reasonable for a 4-screen sim.   

Closing.
