### ISSUE TITLE
refactor "panel"

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/vector-addition#92]
From #71, I switched `ExpandCollapsePanel` to use AccordionBox. I think the module itself if use full, but the classes that extend `ExpandCollapsePanel` are also called "Panels" when they are now technically AccordionBoxes.

Thus, I think we should change the names:
- [x] ExpandCollapsePanel to FixedSizeAccordionBox (this might not be good, but not sure what else to call it)
- [x] VectorValuesPanel to VectorValuesAccordionBox
- [x] CoefficientSelectorPanel to CoefficientSelectorAccordionBox

If these were to change, some of the comments that refer to these classes would need to change as well, and I can help with that.

@pixelzoom thoughts?

**Comment by pixelzoom** [comment]
I think it's a good idea to rename these as you've suggested.  I'll take it from here.

**Comment by pixelzoom** [comment]
I took a little bit of a round-about route to renaming, because I should have started with `ExpandCollapsePanel` (the base class) but didn't.   Here's a summary of the end result:

* ExpandCollapsePanel -> ToggleBox
* VectorValuesPanel -> VectorValuesToggleBox
* CoefficientSelectorPanel -> CoefficientsToggleBox

The doc explains why I chose the name `ToggleBox`:

```
* ToggleBox is a specialized version of AccordionBox that doesn't expand/collapse.  Instead, it toggles between
* 'closed' content and 'open' content, while maintaining a fixed height.
 ```

@brandonLi8 I hope you find these names to be acceptable.

**Comment by brandonLi8** [comment]
@pixelzoom I like it.

**Comment by pixelzoom** [comment]
Excellent.
